on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Aptible
      uses: aptible/aptible-deploy-action@35f9fab6f529d269972b489cfc3b3cba30185e98
      with:
        type: git
        environment: zoo
        app: express
        git_remote: app-65942.on-aptible.com
        private_key: ${{ secrets.PRIVATE_KEY }}
