on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Deploy to Aptible
      uses: aptible/aptible-deploy-action@d94d16b51df3d088e17e2ddd60e7d00021a6fa78
      with:
        type: git
        environment: zoo
        app: express
        git_remote: app-65942.on-aptible.com
        private_key: ${{ secrets.PRIVATE_KEY }}
